name: Shell Commands

on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello KJV"
            - name: miltiline script
              run: |
                  node -v
                  npm -v
                  nvm -v
